# Site settings
title: "苫高専Softech2017 プロコン課題・自由"
email: "takuya.mk96@gmail.com"
description: "苫高専Softech2017 プロコン課題・自由"
baseurl: "/softech-2017" # the subpath of your site, e.g. /blog
url: "https://mktakuya.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: "/:title.html"
twitter_username: mktakuya
github_username:  mktakuya

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
